FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# RUN apt-get update \
#     && apt-get install -y \
#         curl \
#         ca-certificates \
#         gnupg \
#     && curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg \
#     && echo "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
#     && apt-get update \
#     && apt-get install -y postgresql-client-18 \
#     && rm -rf /var/lib/apt/lists/*


# Set working directory
WORKDIR /app

# Copy project files
COPY . .


RUN ls

# Install afterchive in development mode
# This installs it as a command
RUN pip install -e .[postgres]

# Keep container running
CMD ["tail", "-f", "/dev/null"]