FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

RUN ls

# Install afterchive in development mode
# This installs it as a command
RUN pip install -e .[postgres]

# Keep container running
CMD ["tail", "-f", "/dev/null"]